package pi

// extensionTmpl 是 readignore.ts 的模板（text/template）。
//
// 占位 `{{.PatternsAsTSLiterals}}` 由 renderExtension 注入为 TS 字符串字面量数组
// （如 [".env", "!.env.example", "**/id_rsa"]）。匹配引擎 tsMatcherBody 与 pi 引擎
// 共享同一份手写 gitignore 语义实现。
//
// 设计参考 pi 官方 examples/extensions/tool-override.ts：
//   - override 内置 `read`（name:"read" 同名注册）；
//   - execute 内 isBlocked(params.path) → 命中返回 Access denied，否则委托 readFile；
//   - 不 import pi 类型（用 any），零 npm 依赖，使生成 .ts 能在无 pi 环境也通过 tsc 基本检查。
const extensionTmpl = `// readignore extension for pi (generated by readignore CLI; do not edit).
//
// Overrides pi's built-in 'read' tool to block access to paths declared in
// .readignore (gitignore syntax). Blocked paths return "Access denied"; allowed
// paths delegate to a normal read.
//
// Loading: pi auto-loads .pi/extensions/*.ts at startup (loader.ts). Override
// works by registering a tool with the same name as the built-in (tool-override.ts).
//
// Patterns are frozen at generation time (no runtime .readignore read).
//
// Only Node.js built-ins are used (zero third-party npm deps).

import { readFile } from "fs/promises";
import { resolve } from "path";

// Generated patterns (gitignore syntax; '!' negations re-allow via last-match-wins):
const PATTERNS: readonly string[] = {{.PatternsAsTSLiterals}};

` + tsMatcherBody + `

// Minimal shim so this file has zero npm dependencies: avoid importing pi's
// TypeBox/runtime types. The default export receives the pi ExtensionAPI and
// registers an override of the built-in 'read' tool.
export default function (pi: any): void {
	pi.registerTool({
		name: "read", // override built-in read (same name replaces it)
		label: "read (readignore guarded)",
		description:
			"Read the contents of a file. Paths declared in .readignore (.env, secrets, keys, ...) are blocked.",
		parameters: {
			type: "object",
			properties: {
				path: { type: "string", description: "Path to the file to read (relative or absolute)" },
				offset: { type: "number", description: "Line number to start reading from (1-indexed)" },
				limit: { type: "number", description: "Maximum number of lines to read" },
			},
			required: ["path"],
			additionalProperties: false,
		},
		async execute(_toolCallId: string, params: any, _signal: unknown, _onUpdate: unknown, ctx: any) {
			const { path, offset, limit } = params;
			const abs = resolve((ctx && ctx.cwd ? ctx.cwd : process.cwd()), path);

			if (isBlocked(abs) || isBlocked(path)) {
				return {
					content: [
						{
							type: "text",
							text: 'Access denied: "' + path + '" matches a blocked pattern (sensitive file). readignore blocks access to files declared in .readignore.',
						},
					],
					details: { blocked: true },
				};
			}

			// Delegate to a normal read (mirrors pi's built-in read semantics).
			try {
				const content = await readFile(abs, "utf-8");
				const lines = content.split("\n");
				const startLine = offset ? Math.max(0, offset - 1) : 0;
				const endLine = limit ? startLine + limit : lines.length;
				const selected = lines.slice(startLine, endLine);
				let text = selected.join("\n");
				const maxBytes = 50 * 1024;
				if (Buffer.byteLength(text, "utf-8") > maxBytes) {
					text = text.slice(0, maxBytes) + "\n\n[Output truncated at 50KB]";
				}
				return {
					content: [{ type: "text", text }],
					details: { lines: lines.length },
				};
			} catch (error: any) {
				return {
					content: [{ type: "text", text: "Error reading file: " + (error && error.message ? error.message : String(error)) }],
					details: { error: true },
				};
			}
		},
	});
}
`
