package pi

// extensionTmpl 是 readignore.ts 的模板（text/template，v0.3 起无占位符，纯常量）。
//
// v0.3 核心改造：匹配权威统一收敛到 `readignore match`（go-git format/gitignore）。
// 生成的 TS extension 不再内嵌 patterns、不再手写 gitignore matcher——它 override
// pi 内置 `read` 工具，execute 内调 child_process.execFileSync("readignore", ["match", path])：
//   - exit 1（deny） → 命中 .readignore，返回 Access denied；
//   - exit 0（allow） → 未命中（或 .readignore 缺失/解析失败的 fallback），委托 readFile。
//
// .readignore 在运行时由 readignore match 直接读盘（cwd/.readignore），故改 .readignore
// 不必 re-install 即立即生效（动态读核心价值）。
//
// 设计参考 pi 官方 examples/extensions/tool-override.ts：override 内置 `read`（name:"read"
// 同名注册），execute 内判定阻断后委托真正 readFile。不 import pi 类型（用 any），
// 零 npm 依赖，使生成 .ts 能在无 pi 环境也通过 tsc 基本检查。
//
// readignore 不在 PATH 的 fallback：execFileSync 抛错 → 视为放行（不搞死 agent），
// stderr 输出警告便于排查。与 sh 版的 PATH 检测 fallback 策略一致。
const extensionTmpl = `// readignore extension for pi (generated by readignore CLI; do not edit).
//
// Overrides pi's built-in 'read' tool to block access to paths declared in
// cwd/.readignore (gitignore syntax). Blocking is delegated to the ` + "`readignore match`" + `
// subcommand (go-git authority); blocked paths return "Access denied", allowed
// paths delegate to a normal read.
//
// Loading: pi auto-loads .pi/extensions/*.ts at startup (loader.ts). Override
// works by registering a tool with the same name as the built-in (tool-override.ts).
//
// .readignore is read at runtime by ` + "`readignore match`" + ` (NOT frozen at generation time):
// editing .readignore takes effect immediately on the next read — no re-install needed.
//
// Only Node.js built-ins are used (zero third-party npm deps).

import { readFile } from "fs/promises";
import { resolve } from "path";
import { execFileSync } from "child_process";

// isBlocked: ask the readignore binary whether the path matches cwd/.readignore.
//
// Contract: ` + "`readignore match <path>`" + ` exits 1 when the path is denied by
// .readignore, 0 otherwise (including the fallback allow when .readignore is
// absent or fails to parse). Any failure to spawn readignore (e.g. not in PATH)
// is treated as allow + stderr warning — never block the agent on our own fault.
function isBlocked(path: string): boolean {
	try {
		execFileSync("readignore", ["match", path], { stdio: ["ignore", "ignore", "pipe"] });
		return false; // exit 0 = allow
	} catch (e: any) {
		// Non-zero exit: distinguish deny (status 1) from spawn failure (ENOENT, etc.).
		const status = e && typeof e.status === "number" ? e.status : null;
		if (status === 1) {
			return true; // deny
		}
		// Spawn failure (readignore not in PATH, crash, ...): fallback allow.
		const msg = e && e.message ? e.message : String(e);
		process.stderr.write("readignore: failed to run ` + "`readignore match`" + `; hook disabled (allowing). " + msg + "\n");
		return false;
	}
}

// Minimal shim so this file has zero npm dependencies: avoid importing pi's
// TypeBox/runtime types. The default export receives the pi ExtensionAPI and
// registers an override of the built-in 'read' tool.
export default function (pi: any): void {
	pi.registerTool({
		name: "read", // override built-in read (same name replaces it)
		label: "read (readignore guarded)",
		description:
			"Read the contents of a file. Paths declared in .readignore (.env, secrets, keys, ...) are blocked.",
		parameters: {
			type: "object",
			properties: {
				path: { type: "string", description: "Path to the file to read (relative or absolute)" },
				offset: { type: "number", description: "Line number to start reading from (1-indexed)" },
				limit: { type: "number", description: "Maximum number of lines to read" },
			},
			required: ["path"],
			additionalProperties: false,
		},
		async execute(_toolCallId: string, params: any, _signal: unknown, _onUpdate: unknown, ctx: any) {
			const { path, offset, limit } = params;
			const abs = resolve((ctx && ctx.cwd ? ctx.cwd : process.cwd()), path);

			if (isBlocked(abs) || isBlocked(path)) {
				// 静态拒绝消息：不回显 LLM 控制的 path，避免把用户/模型输入反射进输出。
				return {
					content: [
						{
							type: "text",
							text: "Access denied: this path matches a blocked pattern (sensitive file). readignore blocks access to files declared in .readignore.",
						},
					],
					details: { blocked: true },
				};
			}

			// Delegate to a normal read (mirrors pi's built-in read semantics).
			try {
				const content = await readFile(abs, "utf-8");
				const lines = content.split("\n");
				const startLine = offset ? Math.max(0, offset - 1) : 0;
				const endLine = limit ? startLine + limit : lines.length;
				const selected = lines.slice(startLine, endLine);
				let text = selected.join("\n");
				const maxBytes = 50 * 1024;
				if (Buffer.byteLength(text, "utf-8") > maxBytes) {
					text = text.slice(0, maxBytes) + "\n\n[Output truncated at 50KB]";
				}
				return {
					content: [{ type: "text", text }],
					details: { lines: lines.length },
				};
			} catch (error: any) {
				return {
					content: [{ type: "text", text: "Error reading file: " + (error && error.message ? error.message : String(error)) }],
					details: { error: true },
				};
			}
		},
	});
}
`
